### ISSUE TITLE
MakeIt.bat files question

### ISSUE THREAD

**Issue by foliage-burner** [bucanero/ps3iso-utils#2]
Hey @bucanero, do you know if any of this tools require original PS3SDK or PSL1GHT to compile? Otherwise, I think setting the path to them might be unnecessary in the MakeIt.bat files, and might even lead to compilation problems.

I definitely know that makeps3iso does not require any additional SDK to compile; don't know about the others. If none of the other tools have that requirement, it might just be better to delete these bat files and just compile the tools by running make.

**Comment by bucanero** [comment]
No, none of these tools require a PS3 SDK (they're just PC tools that handle ISO files on a computer)
I've seen those `MakeIt.bat` files in many ps3 projects by Hermes/Estwald, so I assume that he was just copying the `.bat`s around when he worked in his homebrew projects.

Yes, I think it's alright to remove those files, they're only meant for Windows and even in that case, the user can build the binaries by running `make`. (I uploaded all the original files untouched, when I updated the sources to support macOS)
