### ISSUE TITLE
Malware?

### ISSUE THREAD

**Issue by elPrimoDorado** [bucanero/ps3iso-utils#6]
![image](https://user-images.githubusercontent.com/39572347/235383492-73dce616-bf69-4e3d-97d3-206b323bd30b.png)
VirusTotal flagged the file as virus :/

**Comment by ASOwnerYT** [comment]
Only 1 random security vendor flagged the file. If this was malware more security vendors would flag it. So no, this open-source project is almost definitely not a virus, if you are really worried you can look at the code yourself or get someone else you trust to look at it. Hope this helps :)

**Comment by bucanero** [comment]
Build the tools from the source code if you have any concerns.
