### ISSUE TITLE
Im new to this

### ISSUE THREAD

**Issue by ben401rs** [bucanero/ps3iso-utils#7]
im using the automatic bat from the folder, it doesnt seem to asked where can i put the completed iso, once im done doing it i cant seem to find and pinpoint where exactly is it stored by default?

**Comment by bucanero** [comment]
there are no "bat" files in the latest release, it's a command line tool and you need to execute from a command prompt, then specify the path to a folder where you have a ps3 game folder.

Be sure to download the release for your OS (windows, linux, mac) here:
https://github.com/bucanero/ps3iso-utils/releases/tag/277db7de
