### ISSUE TITLE
[Question] Maintenance status and AUR packaging

### ISSUE THREAD

**Issue by itshog** [bucanero/ps3iso-utils#8]
First of all, thank you for the great work! I just wanted to ask: is the project still active? The last commit was 2 years ago, and this may lead someone to think that the project has been abandoned, but maybe the program is considered feature-complete so no other development is expected. In both cases, IMO, it should be mentioned in the README, so that users don't mistake a completed project for an abandoned one or viceversa.

On that note, a while ago I created an [AUR package](https://aur.archlinux.org/packages/ps3iso-utils-git) for installing the program on Arch Linux, so if the project has been abandoned maybe I should delete the package. Also, I now realize that maybe I should have contacted the original developers of the software before trying to package it, and I excuse myself for not doing so. Anyway, I'm asking it now: are the developers OK with this package being on the AUR?

**Comment by bucanero** [comment]
the tools are considered feature-complete (any ISO built with these tools work without issues on real PS3 hardware) so unless specific bugs are reported, there won't be further development from my side.

Regarding your question, I can't answer for Estwald (original author), but I've no issues with your AUR package.
